### ISSUE TITLE
Una nota sulla source

### ISSUE THREAD

**Issue by aborruso** [aborruso/Twitter2RAP#10]
Ciao @pigreco inserisci come commento [qui](https://github.com/aborruso/Twitter2RAP/blob/ff1dbc1f75072aee36675bec8010ca104d664d2f/script/script_tw2RAP_count.sh#L3)  l'URL del CSV che fa da sorgente?

E lo fai in tutti gli script in cui usi un CSV di cui è noto l'URL??

Grazie

**Comment by pigreco** [comment]
@aborruso 
fatto

**Comment by aborruso** [comment]
In questi casi, passa al Close direttamente tu :)
