### ISSUE TITLE
recuperare le segnalazioni fatte tramite la app di RAP

### ISSUE THREAD

**Issue by aborruso** [aborruso/Twitter2RAP#7]

**Comment by aborruso** [comment]
Eccole qui https://data.world/opendatasicilia/tw2rap/workspace/file?filename=segnalazioniAppRAP.csv

Ci sono da fare le pulizie del caso (coordinate senza senso, ecc.)

**Comment by pigreco** [comment]
@aborruso 
ho creato una query per ottenere tutti i record con coord != 0
https://query.data.world/s/25kfw3if4utktcyaljr73dil5kttcq

**Comment by pigreco** [comment]
@aborruso 
la query di prima non ha più senso in quanto ho estratto tutte quelle che ricadono nel bound box di Palermo, 
https://query.data.world/s/zlahbnap4zqabt54puercx54jmj7uu
![image](https://user-images.githubusercontent.com/7631137/45114731-0daff180-b14e-11e8-91ff-a01e384444f7.png)
NB: alcuni punti ricadono nel bounds box ma non nel comune di Palermo

**Comment by pigreco** [comment]
@aborruso 
allego db sqlite con tre tabelle: segnalazioni_originali; segnalazioni (corrette); quartieri
[db_appRAP.zip](https://github.com/aborruso/Twitter2RAP/files/2354230/db_appRAP.zip)

**Comment by aborruso** [comment]
@pigreco l'ideale sarebbe fare uno script che al lancio fa tutto.

Perché i dati che messo su data.world si aggiorneranno ogni settimana. Te lo posso assegnare come task??

**Comment by pigreco** [comment]
> @pigreco l'ideale sarebbe fare uno script che al lancio fa tutto.

> Perché  i dati che messo su data.world si aggiorneranno ogni settimana. Te lo posso assegnare come task??

@aborruso 
certo che puoi assegnarmi questo task.
