### ISSUE TITLE
Creare script che fa un po' di geoconteggi sui dati della app di RAP

### ISSUE THREAD

**Issue by aborruso** [aborruso/Twitter2RAP#8]
Dal dataset di RAP https://data.world/opendatasicilia/tw2rap/workspace/file?filename=segnalazioniAppRAP.csv conteggi per quartieri

E tutto quello che pensi di geo poter fare

**Comment by pigreco** [comment]
@aborruso 
ho creato e caricato lo [script](https://github.com/aborruso/Twitter2RAP/blob/master/script/script_appRAP.sh), il db_appRAP che contiene i quartieri e l'output del tuo script rap.sh e la tabella della popolazione per quartieri 2014;
ho aggiornato il file README.md della stessa cartella

**Comment by aborruso** [comment]
Grazie
